language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.14.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y binutils-dev libunwind8-dev

install:
  - git clone https://github.com/bitcoin/secp256k1.git
  - cd secp256k1
  - ./autogen.sh && ./configure && make && sudo make install
  - sudo ldconfig /usr/local/lib
  - cd ..

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --features=bitcoinconsensus
  - cargo test --verbose --features=bitcoinconsensus
  - if [ "$(rustup show | grep default | grep stable)" != "" ]; then cd fuzz && cargo test --verbose && ./travis-fuzz.sh; fi
