
[package]
name = "bitcoin"
version = "0.9.1"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
homepage = "https://github.com/apoelstra/rust-bitcoin/"
repository = "https://github.com/apoelstra/rust-bitcoin/"
documentation = "https://www.wpsoftware.net/rustdoc/bitcoin/"
description = "General purpose library for using and interoperating with Bitcoin and other cryptocurrencies."
keywords = [ "crypto", "bitcoin" ]
readme = "README.md"

[lib]
name = "bitcoin"
path = "src/lib.rs"

[features]
# Compile broken and complicated script interpreter, as well as
# an unspendability checker which is not broken (I think) but is
# a huge pile of unreviewed code
broken_consensus_code = []

[dependencies]
byteorder = "0.3"
num = "0.1"
rand = "0.3"
rust-crypto = "0.2"
rustc-serialize = "0.3"
secp256k1 = "0.6"
serde = "0.6"
strason = "0.3"

[dependencies.jsonrpc]
version = "0.8" # for serde macros
default-features = false

